.travis.yml, README.md
=> Fix travis config and build link.

src/index.html, src/js/gumhandler.js
My computer at work does not have a microphone or a camera plugged in, so I get a false error message. This adds an appropriate error message for this case.
=> Added the no device error

README.md
Thought it would make sense to add a link to TestRTC or WebRTC troubleshooter ;)
=> Add link to WebRTC troubleshooter

src/index.html, src/js/gumhandler.js
I did not cover the no device scenario properly. Also since it is now possible to continue without any device I removed the the no device error dialog as the getUserMedia error reason is printed on the dialog which has the bypass button.
Thanks to henrika@ for discovering and informing me about this.
=> Fixed no device scenario

src/ui/report-dialog.html
=> Updated report upload success text

src/js/report.js, src/js/util.js
I first thought there would be tons of errors but turned out to be just this, phew ;) Fixes #68.
=> Fixed jscs errors

build/jshintrc, src/js/call.js, src/js/camresolutionstest.js, src/js/util.js
Temporary work-around for these tests when running FF (it is bad the way that the tests fails at the moment).
=> Made 'Check xxx resolution' tests not stop testrtc when running in ff

src/ui/gum-handler.html
Fixes #91.
I will also make a separate PR where we use navigator.mediaDevices when available (works on both Chrome and firefox).
=> Fix spelling mistake

app.yaml, src/index.html
The 404 favicon error has bothered me for a long time......
=> Fix favicon

Gruntfile.js, package.json
Fixes issues with vulcanized version of testrtc after updating to polymer 1.0.0
=> Update grunt-vulcanize to 1.0.0

src/js/bandwidth_test.js
Fixes #103 
I decided to just modify the existing Video bandwidth test for this.
More to come later....
=> Add packet lost stats, change reportSuccess to reportInfo for most stats in the Video Bandwidth test

bower.json, src/js/camresolutionstest.js
=> Properly end Check resolution tests

src/js/bandwidth_test.js, test/sanity-test.js
This covers the Video bandwidth and Video throughput tests only, will do network latency tests in separate PR (even thought it's in the same file).
=> Pass the test object to Video bandwidth and Video throughput tests

src/js/nettest.js
=> Check that is params !== null

src/js/camresolutionstest.js
Fixes https://github.com/webrtc/samples/issues/684
=> Add missing bind to the videoTrack events

src/js/camresolutionstest.js
=> Check if event handlers are supported and fix refactor error

src/manual/iframe-apprtc/index.html
Fixes https://github.com/webrtc/apprtc/issues/225.
=> Change to appr.tc URL in the iframe-apprtc test page

src/js/camresolutionstest.js
Fixes #170 (the first camera test that is)
=> Change from error to warning for video mute event

src/manual/peer2peer/index.html, src/manual/peer2peer/js/main.js
Fixes #172 
Note that it did use adapter.js but old style api's. This updates getUserMedia to use promises and getSources to enumerateDevices.
=> Update peer2 peer

Gruntfile.js, app.yaml, package.json, src/js/call.js, src/js/nettest.js, testrtc.py
Use a new turn service.
**Purpose**
Replace flaky CEOD service.
=> Use new turn service instead of CEOD

src/js/nettest.js
Noticed a lint error in a different PR unrelated to it (I believe I introduced this).
**Purpose**
=> Fixing lint error

src/manual/peer2peer/js/main.js
=> Update to use the new adapter.js

src/js/call.js
=> Fetch ice credentials once per session or if they are expired

src/js/call.js, src/js/nettest.js, src/manual/multiple-video-devices/js/main.js, src/manual/peer2peer/js/main.js
same as https://github.com/webrtc/samples/pull/789 -- i'm shooting at anything right now :-)
The bind+this in the first chunk made me think for a minute but it looks ok.
=> apply promisify codemod

README.md
=> Remove non vulcanized steps in README

src/manual/peer2peer/extension/background.js
i heard 'tab' is cool... but I can't see any difference?!
=> add tab option

package.json, src/js/ssim.js, src/manual/index.html, src/manual/multiple-peerconnections/index.html, src/manual/multiple-peerconnections/js/main.js
Add a test page with multiple peerconnections.
**Purpose**
This page is a test page to stress-test WebRTC using several peerconnections in the same page. The geal is to create a WebRTC performance test that would've caught a regression in CfM. 
See:
https://bugs.chromium.org/p/chromium/issues/detail?id=651820
=> Add a test page with multiple peerconnections.

src/manual/multiple-peerconnections/index.html, src/manual/multiple-peerconnections/js/main.js
Format the page a bit better, and add support for googCpuOveruseDetection
**Purpose**
Improvement of the stress-test page for telemetry tests in Chromium for WebRTC
=> Add support for setting up googCpuOveruseDetection.

package.json
We were using an old version which had got lots of warnings on newer node versions.
**Purpose**
=> Update bower version

ISSUE_TEMPLATE.md
=> Remove description from the issue template.

README.md
=> Fix wording in Readme

package.json
fixes #182 (hopefully)
(cause marionette/geckodriver et al)
=> test: bump utils

.travis.yml, package-lock.json, package.json, src/js/bandwidth_test.js, src/js/call.js, src/js/camresolutionstest.js, src/js/stats.js, src/js/util.js
Get the stats working again for TestRTC
I will revisit this as I realized when I had done lots of work already that this approach is not scalable. Will do a proper design doc exploring the different getStats reports available from Chrome and Firefox.
**Purpose**
Fix stats temporarily by using a modified version of enumerateStats from appr.tc
=> Fix stats somewhat for Chrome

app.yaml
=> remove unsupported attributes (for gcloud deploy)
