- app.yaml
- testrtc.py
The previous setting worked on a local appengine, but not in the real deploy as app.yaml cannot reference files not under the directory it is served from.
> Fixed app.yaml and testrtc.py location to work on real appengine.

- src/css/main_nolint.css
- src/index.html
- src/js/bandwidth_test.js
- src/js/gumhandler.js
- src/js/main.js
Some users only have one media device, either camera or microphone. This allows them to continue and test will fail as usual.
Also added a bypass button allowing the user to continue when no devices are detected or permission has been denied which will allow at least the majority of network tests to be run.
Did some small cleanups as well.
Fixes #31
> Allow devices with only 1 media device type and possibilty to continue without any media devices

- src/js/mictest.js
Calculate the Root Mean Square, as opposed to Root Absolute Mean. Also, getting to know the GitHub workflow.
> Fix RMS calculation in mictest.js

- src/js/main.js
- src/js/mictest.js
- Allow progress bars to be cancelled.
- Mic test will run for up to 5s, or until 2s of non-silent audio has been collected.
- Collect and analyze more than the very last input buffer.
- Compute peak level, maximum RMS level and detect clipping.
- Improved mono signal detection.
> Mictestfix

- cron.yml
- src/css/main_nolint.css
- src/index.html
- src/js/report.js
- src/ui/report-dialog.html
- testrtc.py
* Summary of changes:
* Creates a file blob of type text/plain
* Fetches the Blobstore upload URL in a HEAD request
* Uploads the file blob in a form-data POST request using the URL from aforementioned HEAD request/response.
* Log download URL is appended to the Chromium bug report template.
* File bug/upload file button is disabled after successful upload. Closing the bug report dialog resets this state and opening the bug report dialog again allows the user to upload a log file and file a new bug.
* GAE Cron job setup to clean logs older than 30 days every 24h.
* Questions:
* Should we restrict access to the log files? Can add admin only access on the serve/ handler (GAE admin).
* Currently opens a new tab to the Chromium bug tracker when filing a bug, this can be blocked by the popup …
> Add log file upload and download mechanism using blobstore

- src/js/bandwidth_test.js
We should attempt to open the camera in 720p for the bandwidth test to better test the ramp-up time to higher bitrates.
> Open the camera in 720p for the bandwidth test.

- .travis.yml
- bower.json
- src/manual/peer2peer/js/main.js
> Peer2peer - Fix setLocalDescription parsing error when forceIsac is used

- bower.json
Fixes #89 
I just needed to select a specific webcomponents version during bower update.
Question is if I need to pin webcomponents to 0.5.5 due to bower not being able to select a version while installing and might pick up 0.6.3 which will break polymer.
Trying 0.5.0 first, then I'll pin to 0.5.5 if it does not work.
> Change back webcomponents to 0.5

- src/js/main.js
- src/ui/gum-handler.html
Adapter.js now takes care of the shimming of navigator.mediaDevices if it does not exist, it returns real getSources objects if it exist otherwise fake getSources formatted source objects.
It also supports Promise for several methods, including getUserMedia, will look into that in a separate PR.
This enables device selection in Firefox as well, one weird thing though is that Firefox only returns one set of devices, not all that are available on the system. Also not sure if it provides device labels (empty string on HTTP even after gUM approval), will check HTTPS to see if it's works there.
> Use Promise and mediaDevices in favor of getSources

- .bowerrc
- .gitignore
- .travis.yml
- Gruntfile.js
- README.md
- app.yaml
- package.json
- src/index.html
- src/manual/audio-and-video/index.html
- src/manual/multiple-audio/index.html
- src/manual/multiple-peerconnections/index.html
- src/manual/multiple-video-devices/index.html
- src/manual/multiple-video/index.html
- src/manual/peer2peer/index.html
- src/manual/single-audio/index.html
- src/manual/single-video/index.html
- src/ui/gum-dialog.html
- src/ui/gum-handler.html
- src/ui/line-chart.html
- src/ui/report-dialog.html
* Add back package.json so it's more convenient setting up the repo using "npm install"
* Change bower components folder to the components/ in the repo root folder rather than outside the repo, this was done to keep the same folder structure for both the vulcanized and non vulcanized version.
* Add grunt build steps that copies all necessary files to deploy and vulcanizes index.html in a out/ folder.
* The previous bullet and the one before enables developing on an non vulcanized index.html version in src/ (start GAE using the app.yaml in the root) and after running "grunt build" you can run the vulcanized version locally in out/ (start GAE using the app.yaml in out/).
* Fixes #81.
> Add build functionality via grunt

- src/index.html
Without this the path after vulcanize is set to src/images/webrtc-icon...... rather than /images/webrtc-icon which causes a 500.
> Add absolut path so that vulcanize uses the correct path

- Gruntfile.js
Forgot to add the testrtc.py to the build script which handles the bug reporting on the GAE side.
Fixes #101
> add testrtc.py to Gruntfile.js

- test/selenium-lib.js
This will not fix all of the FF failures but it will allow the unsigned webdriver extension to run and in turn expose the next issue (startButton never shows up on travis, but works locally).
I just copied the latest selenium-lib.js from https://github.com/webrtc/samples/blob/master/test/selenium-lib.js.
> update selenium-lib.js from samples/ repo

- bower.json
Currently polymer#1.1.0 does not work in Firefox, I filed an issue in the polymer repo, lets see what they say. Anyway, this will make sure we use polymer#1.0.9 until it works 
*Note: Ignore the branch name (I was going to add more logging when I realized I had forgotten to run bower updated and voila I could reproduce the issue locally as well;))
> Use polymer#1.0.9 until #1.1.0+ works in Firefox

- src/timeline/demo/webrtc-internals-demo.html
- src/timeline/timeline-range-input.html
By being based on 100% rather than pixels this allows the element to have less resize issues.
An issue introduced is that now both sliders can be on the same position. In that case drag will have an effect over the end marker.
> Fix timeline-range-input behaviour on resize.

- README.md
- bower.json
- package.json
- src/index.html
- src/js/bandwidth_test.js
- src/js/call.js
- src/js/conntest.js
- src/js/nettest.js
- src/js/testcasename.js
- src/js/testsuitename.js
- src/ui/testrtc-main.html
I discovered this project while trying to troubleshoot a specific WebRTC connectivity issue - host to host behind the same NAT. Currently testrtc only appears to test WebRTC connectivity through a relay, leaving out the server reflexive and host scenarios. This pull request adds tests for these scenarios, and reduces possible confusion by splitting out the network capability tests and throughput tests into their own suites.
See #125 for prior relevant discussion.
cc @KaptenJansson @andresusanopinto
> Test more webrtc connectivity scenarios

- .travis.yml
- src/js/conntest.js
- src/js/nettest.js
- src/ui/testrtc-suite.html
- src/ui/testrtc-test.html
- test/run-tests
> Increase timeout for connectivity tests and add error message

- src/js/mictest.js
- src/ui/testrtc-test.html
As an FYI this is the first PR part of a series of PR's focusing on reducing globals in TestRTC, specifically it passes the test object from testrtc-test.html to the test so that it can set test status and report directly rather than using the report<status> & setTestFinished() globals.
Also as side objective I will reformat some comments, try to reduce leaking peerConnections (where applicable) and fix other performance issues.
So this means one PR per test.
> Pass test object to mic test

- src/js/nettest.js
Fixed logical error which prevented the Ipv6 test failure being reported as a warning.
Fixes #139
> Make ipv6 failure a warning

- src/js/camresolutionstest.js
- src/js/testcasename.js
Test object is now passed to the tests, also I've changed the tests to be more explicit, i.e. no more looping through an array of resolutions. It just runs the explicit resolutions test and verifies that there are non black moving pixels coming from the camera.
@tednakamura @samdutton @juberti Do you have anything against me removing the test that checks that gUM is successful for 14 resolutions? It actually prevents it from being run properly on Chrome on Android, it crashes Chrome on this test every time since the last 3 or 4 of milestones (since Camera API v2 was introduced I believe). In my opinion it's more of a stress test than anything else.
> Pass test object to camrestest + remove resolution loop test

- src/js/conntest.js
Fixes #150
This used to be the way it worked but was changed in b04bd05902830089aaced1b0663b79a365bd539e, @KaptenJansson assuming this was not on purpose?
> Host connectivity test should not invlove the relay

- .travis.yml
I'm leaving it as an allowed failure so that we can monitor it, when it's green I will remove it from allowed failures.
> Adding firefox beta to allowed failure due to the download location returns 404

- src/js/camresolutionstest.js
fixes #149.
If I remember correctly, previously the code removed all events associated with the video track before calling test done in order to prevent a race condition where on fast machines this.test.done() was executed before the forEach loop finishes and the ended event could not be caught before the object got destroyed, however on slower machines the forEach loop finishes and stops the track thus firing the ended event before this.test.done() is executed and voila, the event has time to fire off an reportError call this failing the test.
Rather than setting all event listeners to null, I just reversed the order to stop the test before stopping the tracks, WDYT? Is this okay or should I explicitly set all events to null in the forEach loop?
> break out test teardown to a separate function

- src/js/nettest.js
Firefox beta no longer support the old createOffer constraints format. I will update this in other repos as well.
> use new createOffer constraints format

- src/js/bandwidth_test.js
A hack for getting getStats to work with Firefox and Chrome. Did not want to spend to much time on it as there is work going on regarding this in adapter.js. Regardless specific stats gathering is required due to them having different names and/or are missing entirely.
Fixes #74.
> Add Firefox specific getStats collection and use promise Based getStats

- Gruntfile.js
- app.yaml
- bower.json
- build/jshintrc
- package.json
- src/index.html
- src/js/bandwidth_test.js
- src/js/call.js
- src/js/camresolutionstest.js
- src/js/conntest.js
- src/manual/audio-and-video/index.html
- src/manual/multiple-audio/index.html
- src/manual/multiple-video-devices/index.html
- src/manual/multiple-video-devices/js/main.js
- src/manual/multiple-video/index.html
- src/manual/peer2peer/index.html
- src/manual/peer2peer/js/main.js
- src/manual/single-audio/index.html
- src/manual/single-video/index.html
- src/ui/gum-handler.html
- src/ui/testrtc-main.html
* SDP has changed in Chrome M50 hence there are more video error correction params we need to remove for the bandwidth tests.
* Update and use latest webrtc-adapter from NPM rather than bower.
* Fix reportFatal (dead code) in call.js
Fixes #178 
**Purpose**
Fix errors seen in Chrome M50
> Fix SDP mangling, fix reportFatal in call.js, use latest webrtc-adapter from NPM rather than bower

- src/js/call.js
- src/js/camresolutionstest.js
Fix getStats error
**Purpose**
Make it run on Firefox
I do want to improve it further so that all tests can use the gatherStats method in call.js but I will do that in a separate PR to keep it simple.
> Improve stats collection in call.js

- src/js/bandwidth_test.js
- src/js/call.js
- src/js/camresolutionstest.js
Use latest adapter.js
Fix yet another issue when gathering stats on firefox (found when updating adapter).
Refactored bandwidth_test.js and cameraresolutiontest.js to use call.js for gathering stats.
**Purpose**
Get the latest adapter.js shimming
Having the stats gathering logic on one place makes it easier update.
> Update to adapter 1.1.0 and use call.js for all stats gathering

- src/manual/peer2peer/extension/background.js
Reverts webrtc/testrtc#212 -- tab is actually passed conditionally for chrome >= 50.
> Revert "add tab option"

- src/manual/peer2peer/extension/background.js
- src/manual/peer2peer/js/main.js
We found that mediaDevices.getUserMedia does a strong check for the existence of requested track.
Namely, if we request an audio track, but Chromium cannot provide, getUserMedia will throw an exception rather than return a video-only stream. This behavior is aligned with the spec definition.
However, this brings some inconvenience in the desktop share with audio area, because on the media picker dialog, the end user could choose to uncheck the audio checkbox, and wish to get a video only stream. To resolve this dilemma, we change the Chromium a little bit to pass the information whether the user has checked or unchecked the audio to the callback function of chooseDesktopMedia, and then let following Javascript react correctly.
This change makes the mannual/peer2peer react …
> Request Audio With Desktop Share Only When The User Approves

- README.md
markdown needs a %20 to encode spaces in urls.
> Unbreak the network latency link

- src/js/call.js
- src/js/main.js
- src/js/ssim.js
- src/js/videoframechecker.js
- test/run-tests.js
- test/sanity-test.js
this got replaced by eslint a while ago
> all: remove references to jshint and jscs

- src/js/bandwidth_test.js
not packet loss indication. See https://tools.ietf.org/html/rfc4585
Arguably, it is an indication for severe packet loss.
@henbos I heard you know a bit about this "statistics" stuff, can you review?
> bandwidth test: PLI is picture loss indication

- README.md
Removed "Other test pages section" from README.md file
**Purpose**
Fix Dead links in testrtc description - that takes users to 404.
> Fix Dead links in testrtc description - Issue #247

- src/js/call.js
getStats does not support a MediaStream as ѕelector, Firefox does not accept this.
@KaptenJansson PTAL
@henbos @alvestrand this will make you 😭
> remove pc.getStats mediaStream selector argument

- src/js/main.js
- src/js/mictest.js
- src/ui/testrtc-main.html
- test/sanity-test.js
Update to use the new api for audioContext and move global audioContext creation to the mictest constructor.
Fixes #267, #261 
**Purpose**
Fix Mic input tests.
> Fix WebAudio init handling

- Gruntfile.js
- src/ui/report-dialog.html
This is no longer used.
**Purpose**
> Remove upload report functionality since its hardly used

- src/js/bandwidth_test.js
- src/js/camresolutionstest.js
- src/js/mictest.js
- src/ui/testrtc-main.html
Remove use of optional constraints format.
Use the global doGetUserMedia function to pickup the device selected in the settings menu for all tests.
**Purpose**
Fix device selection
> Fix device selection
